/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WsToggle {
    'toggledOn': boolean;
  }
}

declare global {


  interface HTMLWsToggleElement extends Components.WsToggle, HTMLStencilElement {}
  var HTMLWsToggleElement: {
    prototype: HTMLWsToggleElement;
    new (): HTMLWsToggleElement;
  };
  interface HTMLElementTagNameMap {
    'ws-toggle': HTMLWsToggleElement;
  }
}

declare namespace LocalJSX {
  interface WsToggle {
    'toggledOn'?: boolean;
  }

  interface IntrinsicElements {
    'ws-toggle': WsToggle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ws-toggle': LocalJSX.WsToggle & JSXBase.HTMLAttributes<HTMLWsToggleElement>;
    }
  }
}


